### ISSUE TITLE
No HTML inside iframe allowed

### ISSUE THREAD

**Issue by akroii** [Tastaturberuf/contao-doccheck-login-bundle#10]
https://github.com/Tastaturberuf/contao-doccheck-login-bundle/blob/bdffa76b313dcefc71d55b7a162ab77b3f59dc8e/src/Resources/contao/templates/mod_doccheck_login.html5#L14

Do we need this?

**Comment by Tastaturberuf** [comment]
Iam not sure if this is a fallback for any reason the browser can't dispay the iframe.

**Comment by akroii** [comment]
iframe are supported in every browser [https://caniuse.com/?search=iframe](https://caniuse.com/?search=iframe). even IE... 😁
even ce_youtube.html does not contain html
[https://github.com/contao/contao/blob/4.x/core-bundle/src/Resources/contao/templates/elements/ce_youtube.html5](https://github.com/contao/contao/blob/4.x/core-bundle/src/Resources/contao/templates/elements/ce_youtube.html5)

maybe we can place it outside of iframe 🤔?

**Comment by Tastaturberuf** [comment]
no then lets remove it completely

**Comment by akroii** [comment]
[https://github.com/Tastaturberuf/contao-doccheck-login-bundle/pull/11](https://github.com/Tastaturberuf/contao-doccheck-login-bundle/pull/11)

**Comment by Tastaturberuf** [comment]
thanks @akroii
