### ISSUE TITLE
Möglichkeit Parameter der Return-URL beizubehalten

### ISSUE THREAD

**Issue by akroii** [Tastaturberuf/contao-doccheck-login-bundle#13]
Hallo Daniel,
wäre es möglich die Parameter, die von DocCheck zurückgeworfen werden beizubehalten?

Also 
https://xxxxxx.de/doccheck-login.html?dc=1&uniquekey=478ac05c52477d89028a3cb315s3f077&dc_single_signon=1&login_id=XXXXXXXX&client_id=XXXXXX&state=%2Fueber-uns.html&strDcLanguage=de&intDcLanguageId=148&dc_timestamp=167145125

und nicht nur :
https://xxxxxx.de/doccheck-login.html
.. am Ende des redirects beizubehalten?
Wir möchten mit Google Analytics noch die Parameter der URL tracken.

Das müsste folgede Änderung im src/Controller/DocCheckLoginController.php sein:
```diff
-      throw new RedirectResponseException($jumpTo->getFrontendUrl());
+      throw new RedirectResponseException($jumpTo->getFrontendUrl().'?'.\Environment::get('queryString'));
```

So erhält man auf der jumpTo-Seite ebenfalls noch die ganzen Parameter der die von DocCheck mitkommen. Was denkst du?
Ich habe es mit dem iframe auch getestet... würde problemlos funktionieren.

**Comment by Tastaturberuf** [comment]
Das ist neu das die was zurück geben oder ist das eine höhere Lizenz?

**Comment by Tastaturberuf** [comment]
Also wenn das nur der Einzeiler ist und bei der Basis-Lizenz nichts kaputt geht, kannst du das gerne einbauen.

**Comment by akroii** [comment]
Soweit ich das weiß, funktioniert das schon in der Basic Variante. Es ist uns vorher noch nicht aufgefallen, weil wir mit dem RedirectResponseException die Parameter überschreiben werden.
Schau gerne mal in deinem Netzwerk-Tab und sende einen Login ab. Natürlich mit der Codeänderung oben.

**Comment by akroii** [comment]
PS: In der Basic Variante gibt es nicht so viele Parameter die nach einem Login geliefert werden. Mein Beispiel oben ist in der Business-Lizenz.
